apiVersion: v1
kind: pod
metadata:
  name: nginx-resources
  namespace: pod-resources
spec:
 containers: 
 - name: nginx
   image: nginx
   resources:
     requests:
       cpu: 200m
       memory: 1Gi 