apiVersion: apps/v1
kind: Deployment
metadata:
  name: web02
  namespace: tct
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
